# Generated by Django 5.2.8 on 2025-12-10 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YearFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(db_index=True, max_length=100, null=True, verbose_name='Год')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('year',),
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('genre', models.CharField(db_index=True, max_length=50)),
                ('description', models.CharField()),
                ('date', models.DateTimeField()),
                ('slug', models.SlugField(max_length=100, unique=100)),
                ('torrent_link', models.URLField(blank=True)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.yearfilter')),
            ],
            options={
                'verbose_name': 'Добавление игры',
            },
        ),
    ]
