# Generated by Django 5.2.8 on 2025-12-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yearfilter',
            options={'ordering': ('year',), 'verbose_name': 'Год', 'verbose_name_plural': 'Года'},
        ),
        migrations.AddField(
            model_name='games',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='game_previev/'),
        ),
    ]
