# Generated by Django 5.2.8 on 2025-11-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40)),
                ('chanel', models.CharField(db_index=True, max_length=40)),
                ('date', models.DateTimeField()),
                ('preview', models.ImageField(blank=True, upload_to='video_previev/')),
                ('slug', models.SlugField(max_length=100, unique=100)),
                ('redirect', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'А вот в процессе и узнаю где это, я забыл.',
            },
        ),
    ]
