# Generated by Django 5.2.8 on 2025-12-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_yearfilter_alter_video_options_video_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yearfilter',
            options={'ordering': ('year',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='yearfilter',
            name='name',
        ),
        migrations.AddField(
            model_name='yearfilter',
            name='year',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='Год'),
        ),
    ]
