# Generated by Django 5.2.8 on 2025-12-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_yearfilter_options_remove_yearfilter_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yearfilter',
            options={'ordering': ('year',), 'verbose_name': 'Год', 'verbose_name_plural': 'Года'},
        ),
    ]
