# Generated by Django 5.2.8 on 2026-01-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_yearfilter_track_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
